export const JENJANG_TINGKAT_MAP: Record<string, Array<{ tingkat: number; label: string; fase: string }>> = {
  PAUD: [{ tingkat: 0, label: 'PAUD / TK (Fase PAUD)', fase: 'PAUD' }],
  SD: [
    { tingkat: 1, label: 'Kelas 1 (Fase A)', fase: 'A' },
    { tingkat: 2, label: 'Kelas 2 (Fase A)', fase: 'A' },
    { tingkat: 3, label: 'Kelas 3 (Fase B)', fase: 'B' },
    { tingkat: 4, label: 'Kelas 4 (Fase B)', fase: 'B' },
    { tingkat: 5, label: 'Kelas 5 (Fase C)', fase: 'C' },
    { tingkat: 6, label: 'Kelas 6 (Fase C)', fase: 'C' },
  ],
  SMP: [
    { tingkat: 7, label: 'Kelas 7 / VII (Fase D)', fase: 'D' },
    { tingkat: 8, label: 'Kelas 8 / VIII (Fase D)', fase: 'D' },
    { tingkat: 9, label: 'Kelas 9 / IX (Fase D)', fase: 'D' },
  ],
  SMA: [
    { tingkat: 10, label: 'Kelas 10 / X (Fase E)', fase: 'E' },
    { tingkat: 11, label: 'Kelas 11 / XI (Fase F)', fase: 'F' },
    { tingkat: 12, label: 'Kelas 12 / XII (Fase F)', fase: 'F' },
  ],
  SMK: [
    { tingkat: 10, label: 'Kelas 10 / X (Fase E)', fase: 'E' },
    { tingkat: 11, label: 'Kelas 11 / XI (Fase F)', fase: 'F' },
    { tingkat: 12, label: 'Kelas 12 / XII (Fase F)', fase: 'F' },
    { tingkat: 13, label: 'Kelas 13 / XIII (Fase F)', fase: 'F' },
  ],
  SLB: [
    { tingkat: 1, label: 'Kelas 1 (Fase A)', fase: 'A' },
    { tingkat: 2, label: 'Kelas 2 (Fase A)', fase: 'A' },
    { tingkat: 3, label: 'Kelas 3 (Fase B)', fase: 'B' },
    { tingkat: 4, label: 'Kelas 4 (Fase B)', fase: 'B' },
    { tingkat: 5, label: 'Kelas 5 (Fase C)', fase: 'C' },
    { tingkat: 6, label: 'Kelas 6 (Fase C)', fase: 'C' },
    { tingkat: 7, label: 'Kelas 7 (Fase D)', fase: 'D' },
    { tingkat: 8, label: 'Kelas 8 (Fase D)', fase: 'D' },
    { tingkat: 9, label: 'Kelas 9 (Fase D)', fase: 'D' },
    { tingkat: 10, label: 'Kelas 10 (Fase E)', fase: 'E' },
    { tingkat: 11, label: 'Kelas 11 (Fase F)', fase: 'F' },
    { tingkat: 12, label: 'Kelas 12 (Fase F)', fase: 'F' },
  ],
  ALL: [
    { tingkat: 1, label: 'Kelas 1 (Fase A)', fase: 'A' },
    { tingkat: 2, label: 'Kelas 2 (Fase A)', fase: 'A' },
    { tingkat: 3, label: 'Kelas 3 (Fase B)', fase: 'B' },
    { tingkat: 4, label: 'Kelas 4 (Fase B)', fase: 'B' },
    { tingkat: 5, label: 'Kelas 5 (Fase C)', fase: 'C' },
    { tingkat: 6, label: 'Kelas 6 (Fase C)', fase: 'C' },
    { tingkat: 7, label: 'Kelas 7 / VII (Fase D)', fase: 'D' },
    { tingkat: 8, label: 'Kelas 8 / VIII (Fase D)', fase: 'D' },
    { tingkat: 9, label: 'Kelas 9 / IX (Fase D)', fase: 'D' },
    { tingkat: 10, label: 'Kelas 10 / X (Fase E)', fase: 'E' },
    { tingkat: 11, label: 'Kelas 11 / XI (Fase F)', fase: 'F' },
    { tingkat: 12, label: 'Kelas 12 / XII (Fase F)', fase: 'F' },
  ]
};
