import { STRUKTUR_CODES } from './organization-structure';

export const STRUKTUR_CAPABILITIES: Record<string, string[]> = {
  [STRUKTUR_CODES.GERBANG]: [
    'attendance.scan',
    'dashboard.view.gerbang',
    'dashboard.view.overview',
    'attendance.gate.tap.entry',
    'attendance.gate.tap.exit',
    'attendance.gate.face.verify',
    'attendance.manage.petugas',
    'attendance.piket.view',
    'academic.activities.types.view',
    'academic.teaching.view',
    'attendance.markGateAbsence',
    'attendance.getNotPresentStudents'
  ],
  [STRUKTUR_CODES.KURIKULUM]: [
    'organization.scope.tenant_wide',
    'dashboard.view.kurikulum',
    'academic.activities.view.grouped',
    'academic.teaching.rekap',
    'curriculum.supervision.manage',
    'curriculum.supervision.view.report',
    'curriculum.supervision.view.schedule',
    'curriculum.supervision.create.record',
    'curriculum.supervision.update.record',
    'curriculum.supervision.delete.record',
    'curriculum.structure.manage',
    'academic.teachers.view.list',
    'academic.teachers.view.detail',
    'academic.teachers.view.history', // Pantau histori mengajar
    'academic.structures.view.list',
    'academic.structures.view.tree',
    'academic.structures.create',
    'academic.structures.update',
    'academic.structures.delete',
    'academic.structures.assign.teacher',
    'academic.structures.revoke.teacher',
    'academic.structures.assign.student',
    'academic.structures.revoke.student',
    'academic.years.view.list',
    'academic.years.create',
    'academic.years.update',
    'academic.years.delete',
    'academic.years.set.active',
    'academic.semesters.view.list',
    'academic.semesters.create',
    'academic.semesters.update',
    'academic.semesters.delete',
    'academic.semesters.set.active',
    'academic.activities.types.view',
    'academic.activities.types.manage',
    'academic.teaching.view',
    'academic.teaching.manage', // Atur pembagian jam mengajar
    'academic.subjects.view.list',
    'academic.subjects.create',
    'academic.subjects.update',
    'academic.subjects.delete',
    'academic.subjects.manage', // Kelola daftar mapel
    'academic.students.view.list',
    'academic.students.view.detail',
    'academic.homeroom.manage', // Penunjukan Wali Kelas
    'attendance.sessions.view.list',
    'attendance.sessions.view.detail',
    'attendance.reports.view',
    'attendance.schedules.view.list',
    'attendance.schedules.manage',
    'attendance.schedules.create',
    'attendance.schedules.update',
    'attendance.schedules.delete',
    'attendance.officers.view',
    'attendance.officers.manage'
  ],
  [STRUKTUR_CODES.KESISWAAN]: [
    'organization.scope.tenant_wide',
    'dashboard.view.kesiswaan',
    "dashboard.view.violation.stats",
    'affairs.violations.report',
    'affairs.violations.update',
    'affairs.violations.delete', // Kesiswaan berhak menghapus pelanggaran
    'affairs.violations.manage', // Hapus/Edit pelanggaran salah input
    'affairs.violations.view.list',
    'affairs.violations.view.detail', // Lihat detail pelanggaran
    "affairs.violation.types.view.list",
    "affairs.violation.types.create", // Kesiswaan kelola jenis pelanggaran
    "affairs.violation.types.update",
    "affairs.violation.types.delete",
    "affairs.violation.types.manage",
    'academic.students.view.list',
    'academic.students.view.detail',
    'academic.students.view.history',
    'academic.teachers.view.list',
    'academic.structures.view.list',
    'attendance.student.view.stats',
    'attendance.piket.manage',
    'attendance.piket.view',
    'attendance.sessions.view.list',
    'attendance.sessions.update.attendance', // Kesiswaan bisa koreksi absensi massal
    'attendance.sessions.tap',
    'attendance.reports.view',
    'notify.announcements.manage' // Sebar pengumuman kesiswaan
  ],
  [STRUKTUR_CODES.KEPALA_SEKOLAH]: [
    'organization.scope.tenant_wide',
    'dashboard.view.kepsek',
    "dashboard.view.student.stats",
    "dashboard.view.teacher.attendance",
    "dashboard.view.violation.stats",
    "dashboard.view.financial.summary",
    'academic.teachers.view.list',
    'academic.teachers.view.detail',
    'academic.structures.view.list',
    'academic.subjects.view.list',
    'academic.students.view.list',
    'academic.students.view.detail',
    'academic.students.view.history',
    'academic.years.view.list',
    'academic.semesters.view.list',
    'academic.homeroom.manage', // Untuk melihat penugasan Wali Kelas
    'curriculum.supervision.view.schedule',
    'curriculum.supervision.view.report',
    'curriculum.supervision.create.record', // Kepsek selaku supervisor utama
    'curriculum.supervision.update.record',
    'curriculum.supervision.delete.record',
    'affairs.violations.view.list',
    'affairs.violations.view.detail',
    'attendance.piket.view',
    'attendance.reports.view',
    'attendance.sessions.view.list',
    'attendance.sessions.view.detail',
    'attendance.recap.view.daily',
    'attendance.recap.view.monthly',
    'attendance.recap.view.global',
    'sarpras.inventory.view.list',
    'sarpras.loans.view.list',
    'sarpras.repairs.view.list',
    'billing.subscriptions.view.active', // Kepsek pantau status langganan aplikasi
    'dashboard.view.hubin',
    'hubin.pkl.view.list',
    'hubin.view.pkl',
    'hubin.absensi.view.history',
    'hubin.absensi.recap',
    'hubin.mou.view.list',
    'reports.hubin.view',
    'affairs.violation.types.view.list'
  ],
  [STRUKTUR_CODES.WALIKELAS]: [
    'organization.scope.unit_restricted',
    'dashboard.view.walikelas',
    'dashboard.view.overview',
    'core.tenants.view.detail',
    'academic.students.view.list',
    'academic.students.view.detail', // Tambahan: Lihat detail (termasuk ortu)
    'attendance.manage.petugas',
    'attendance.recap.view.daily',
    'attendance.recap.view.monthly',
    'attendance.reports.view',
    'affairs.violations.view.list',
    'affairs.violations.report', // Tambahan: Wali kelas bisa lapor pelanggaran anak buahnya
    'affairs.violation.types.view.list',
    'affairs.violations.view.detail',
    'academic.teaching.view',
    'academic.structures.view.list',
    'academic.structures.view.tree',
    'academic.homeroom.manage',
    'academic.students.view.history',
    'hubin.absensi.view.history',
    'attendance.schedules.view.list',
    'attendance.schedules.manage',
    'attendance.schedules.create',
    'attendance.schedules.update',
    'attendance.schedules.delete',
    'attendance.officers.view',
    'attendance.officers.manage',
    'attendance.sessions.view.detail',
    'attendance.sessions.update.attendance', // Tambahan: Validasi Izin/Sakit
    'attendance.sessions.tap',
    'attendance.sessions.update.journal',
    'attendance.markGateAbsence',
    'attendance.getNotPresentStudents'
  ],
  [STRUKTUR_CODES.PETUGAS_KELAS]: [
    'organization.scope.unit_restricted',
    'dashboard.view.petugas',
    'dashboard.view.overview',
    'core.tenants.view.detail',
    'academic.students.view.list',
    'academic.students.view.detail',
    'academic.teachers.view.list', // Tambahan: Referensi Dropdown Guru
    'academic.subjects.view.list', // Tambahan: Referensi Dropdown Mapel
    'academic.structures.view.list', // Tambahan: Referensi Dropdown Kelas
    'academic.teaching.view',
    'attendance.schedules.view.list',
    'attendance.schedules.manage',
    'attendance.schedules.create',
    'attendance.schedules.update',
    'attendance.schedules.delete',
    'attendance.sessions.view.list',
    'attendance.sessions.view.detail',
    'attendance.sessions.create',
    'attendance.sessions.update',
    'attendance.sessions.delete',
    'attendance.sessions.update.attendance',
    'attendance.sessions.tap',
    'attendance.sessions.update.journal',
    'attendance.recap.view.daily',
    'attendance.recap.view.monthly',
    'attendance.monitoring.view.live.status',
    'attendance.markGateAbsence',
    'attendance.getNotPresentStudents',
    'dashboard.view.teacher.attendance'
  ],


  [STRUKTUR_CODES.HUBIN]: [
    'organization.scope.tenant_wide',
    'dashboard.view.hubin',
    'hubin.pkl.view.list',
    'hubin.mou.view.list',
    'hubin.partners.manage',
    'hubin.absensi.recap',
    'hubin.absensi.view.history',
    'hubin.absensi.verify',
    'hubin.view.pkl',
    'academic.students.view.list',
    'academic.students.view.detail',
    'hubin.guidance.manage',
    'hubin.logbook.manage',
    'reports.hubin.view'
  ],
  [STRUKTUR_CODES.SARPRAS]: [
    'organization.scope.tenant_wide',
    'dashboard.view.sarpras',
    'sarpras.inventory.view.list',
    'sarpras.inventory.manage',
    'sarpras.loans.view.list',
    'sarpras.loans.manage',
    'sarpras.repairs.view.list',
    'sarpras.repairs.manage'
  ],
  [STRUKTUR_CODES.TOOLMAN]: [
    'organization.scope.unit_restricted',
    'dashboard.view.sarpras',
    'sarpras.inventory.view.list',
    'sarpras.inventory.manage',
    'sarpras.loans.view.list',
    'sarpras.loans.manage',
    'sarpras.repairs.view.list',
    'sarpras.repairs.manage'
  ],
  [STRUKTUR_CODES.BPBK]: [
    'organization.scope.tenant_wide',
    'dashboard.view.kesiswaan',
    'dashboard.view.violation.stats',
    'affairs.violations.report',
    'affairs.violations.update',
    'affairs.violations.view.list',
    'affairs.violations.view.detail',
    'affairs.violation.types.view.list',
    'academic.students.view.list',
    'academic.students.view.detail',
    'academic.students.view.history',
    'attendance.student.view.stats',
    'attendance.recap.view.daily',
    'attendance.recap.view.monthly', // Tambahan: Histori bulanan untuk konseling
    'attendance.reports.view' // Tambahan: Rekap global untuk deteksi dini
  ],
  [STRUKTUR_CODES.BKK]: [
    'organization.scope.tenant_wide',
    'dashboard.view.hubin',
    'hubin.partners.manage',
    'academic.students.view.list',
    'academic.students.view.detail',
    'hubin.pkl.view.list',
    'hubin.mou.view.list'
  ],
  [STRUKTUR_CODES.KABENG]: [
    'organization.scope.unit_restricted',
    'dashboard.view.sarpras',
    'sarpras.inventory.view.list',
    'sarpras.inventory.manage',
    'sarpras.loans.view.list',
    'sarpras.loans.manage',
    'sarpras.repairs.view.list',
    'sarpras.repairs.manage'
  ],
  [STRUKTUR_CODES.TU]: [
    'organization.scope.tenant_wide',
    'dashboard.view.tu',
    'tu.letters.manage',
    'tu.staff.view.list',
    'tu.staff.manage', // Tambahan: TU kelola data kepegawaian
    'academic.students.view.list',
    'academic.students.manage', // Tambahan: TU kelola data induk siswa
    'academic.teachers.view.list',
    'academic.teachers.manage', // Tambahan: TU kelola data induk guru
    'billing.invoices.view.list', // Tambahan: TU pantau tagihan/pembayaran
    'billing.invoices.generate'
  ],
  [STRUKTUR_CODES.KAPROG]: [
    'organization.scope.unit_restricted',
    'academic.activities.view.grouped',
    'academic.teaching.rekap',
    'attendance.piket.manage',
    'attendance.piket.view',
    'academic.students.view.list', // Tambahan: Kaprog pantau siswa di jurusannya
    'dashboard.view.hubin',
    'hubin.pkl.view.list',
    'hubin.view.pkl',
    'hubin.absensi.view.history',
    'hubin.absensi.recap',
    'hubin.mou.view.list',
    'affairs.violations.view.list',
    'affairs.violations.view.detail',
    'affairs.violation.types.view.list',
    'dashboard.view.violation.stats',
    // Monitoring Akademik
    'academic.teachers.view.list',
    'academic.teachers.view.detail',
    'academic.structures.view.list',
    'academic.structures.view.tree',
    // Monitoring Kehadiran
    'attendance.recap.view.daily',
    'attendance.recap.view.monthly',
    'attendance.reports.view',
    'attendance.sessions.view.list',
    'attendance.sessions.view.detail',
    // Monitoring Sarpras
    'dashboard.view.sarpras',
    'sarpras.inventory.view.list',
    'sarpras.loans.view.list',
    'sarpras.repairs.view.list'
  ],
  [STRUKTUR_CODES.BENDAHARA_KOPERASI]: [
    'academic.structures.view.tree',
    'cooperative.dashboard.view.overview',
    'cooperative.announcements.view.list',
    'cooperative.members.view.list',
    'cooperative.members.view.detail',
    'cooperative.members.create',
    'cooperative.members.update',
    'cooperative.members.delete',
    'cooperative.members.manage',
    'cooperative.savings.create',
    'cooperative.savings.deposit',
    'cooperative.savings.withdraw',
    'cooperative.savings.view.list',
    'cooperative.savings.view.detail',
    'cooperative.savings.view.history',
    'cooperative.points.view',
    'cooperative.store.view.catalog',
    'cooperative.loans.view.list',
    'cooperative.loans.apply',
    'cooperative.loans.repay',
    'cooperative.reports.view.financial',
    'cooperative.reports.view.daily',
    'cooperative.reports.view.monthly',
    // Kelola Skema/Konfigurasi Simpanan
    'cooperative.savings.types.manage',
    'cooperative.savings.manage',
    // Kelola Skema Pinjaman & Verifikasi Detail
    'cooperative.loans.view.detail',
    'cooperative.loans.types.manage',
    // Rekonsiliasi Toko Koperasi
    'cooperative.store.orders.view.list',
    'cooperative.store.transactions.view',
    'cooperative.store.products.view.list',
    'cooperative.store.products.view.detail',
    // Konfigurasi Loyalitas Poin
    'cooperative.points.manage',
    // Manajemen SHU Dedikatif
    'cooperative.shu.manage',
    'cooperative.shu.calculate',
    'cooperative.shu.view.report',
    // Manajemen Pengaturan Koperasi
    'cooperative.settings.view',
    'cooperative.vouchers.view.list',
    'cooperative.tickets.view.list',
    'cooperative.tickets.view.detail'
  ],
  [STRUKTUR_CODES.KETUA_KOPERASI]: [
    'academic.structures.view.tree',
    'cooperative.dashboard.view.overview',
    'cooperative.announcements.view.list',
    'cooperative.members.view.list',
    'cooperative.members.view.detail',
    'cooperative.members.create',
    'cooperative.members.update',
    'cooperative.members.delete',
    'cooperative.members.manage',
    'cooperative.savings.view.history',
    'cooperative.points.view',
    'cooperative.store.view.catalog',
    'cooperative.loans.view.list',
    'cooperative.loans.apply',
    'cooperative.loans.approve',
    'cooperative.loans.repay',
    'cooperative.reports.view.financial',
    'cooperative.reports.view.daily',
    'cooperative.reports.view.monthly',
    // Monitoring & Keputusan Pinjaman
    'cooperative.loans.view.detail',
    'cooperative.loans.reject',
    // Monitoring Simpanan
    'cooperative.savings.view.list',
    'cooperative.savings.view.detail',
    // Supervisi Toko
    'cooperative.store.orders.view.list',
    'cooperative.store.products.view.list',
    'cooperative.store.products.view.detail',
    // Monitoring Keluhan (Tickets)
    'cooperative.tickets.view.list',
    'cooperative.tickets.view.detail',
    // Manajemen SHU Dedikatif
    'cooperative.shu.approve',
    'cooperative.shu.view.report',
    // Manajemen Pengaturan Koperasi
    'cooperative.settings.view',
    'cooperative.vouchers.view.list'
  ],
  [STRUKTUR_CODES.SEKRETARIS_KOPERASI]: [
    'academic.structures.view.tree',
    'cooperative.dashboard.view.overview',
    'cooperative.announcements.view.list',
    'cooperative.announcements.create',
    'cooperative.announcements.delete',
    'cooperative.members.view.list',
    'cooperative.members.view.detail',
    'cooperative.members.create',
    'cooperative.members.update',
    'cooperative.members.delete',
    'cooperative.members.manage',
    'cooperative.savings.view.history',
    'cooperative.points.view',
    'cooperative.store.view.catalog',
    'cooperative.loans.apply',
    'cooperative.vouchers.manage',
    'cooperative.vouchers.view.list',
    'cooperative.tickets.create',
    'cooperative.tickets.reply',
    'cooperative.tickets.update.status',
    'cooperative.tickets.view.detail',
    'cooperative.tickets.view.list',
    // Administrasi Status Keanggotaan
    'cooperative.members.activate',
    'cooperative.members.deactivate',
    'cooperative.members.view.status',
    // Investigasi Keluhan (Read-Only)
    'cooperative.savings.view.list',
    'cooperative.savings.view.detail',
    'cooperative.loans.view.list',
    'cooperative.loans.view.detail',
    'cooperative.store.orders.view.list',
    'cooperative.store.products.view.list',
    'cooperative.store.products.view.detail'
  ],
  [STRUKTUR_CODES.MANAJER_TOKO_KOPERASI]: [
    'academic.structures.view.tree',
    'cooperative.dashboard.view.overview',
    'cooperative.announcements.view.list',
    'cooperative.savings.view.history',
    'cooperative.members.view.list',
    'cooperative.members.view.detail',
    'cooperative.points.view',
    'cooperative.loans.apply',
    'cooperative.store.view.catalog',
    'cooperative.store.orders.manage',
    'cooperative.store.orders.view.list',
    'cooperative.store.inventory.manage',
    'cooperative.store.products.view.list',
    'cooperative.store.products.view.detail',
    'cooperative.store.products.create',
    'cooperative.store.products.update',
    'cooperative.store.products.delete',
    // Kelola Kategori Toko & Riwayat Transaksi POS
    'cooperative.store.categories.manage',
    'cooperative.store.transactions.view',
    // Fitur Promosi Voucer
    'cooperative.vouchers.manage',
    'cooperative.vouchers.view.list',
    // Layanan Produk Digital PPOB di Kasir
    'cooperative.ppob.transact',
    'cooperative.ppob.manage.products',
    'cooperative.ppob.view.products',
    'cooperative.tickets.view.list',
    'cooperative.tickets.view.detail',
    'cooperative.tickets.reply'
  ],
  [STRUKTUR_CODES.PENGAWAS_KOPERASI]: [
    'academic.structures.view.tree',
    'cooperative.dashboard.view.overview',
    'cooperative.announcements.view.list',
    'cooperative.members.view.list',
    'cooperative.members.view.detail',
    'cooperative.savings.view.list',
    'cooperative.savings.view.history',
    'cooperative.points.view',
    'cooperative.store.view.catalog',
    'cooperative.loans.view.list',
    'cooperative.loans.apply',
    'cooperative.reports.view.financial',
    'cooperative.reports.view.daily',
    'cooperative.reports.view.monthly',
    // Audit Simpanan & Pinjaman (Read-Only Detail)
    'cooperative.savings.view.detail',
    'cooperative.loans.view.detail',
    // Audit Toko Koperasi & Transaksi POS (Read-Only)
    'cooperative.store.orders.view.list',
    'cooperative.store.transactions.view',
    'cooperative.store.products.view.list',
    'cooperative.store.products.view.detail',
    // Audit Kualitas Pelayanan (Tickets Read-Only)
    'cooperative.tickets.view.list',
    'cooperative.tickets.view.detail',
    // Audit Laporan SHU & Pengaturan (Read-Only)
    'cooperative.shu.view.report',
    'cooperative.settings.view',
    'cooperative.vouchers.view.list'
  ]
};
