-- AlterTable
ALTER TABLE "Billing" ALTER COLUMN "billing_date" SET DATA TYPE TIMESTAMPTZ USING "billing_date" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "issue_date" SET DATA TYPE TIMESTAMPTZ USING "issue_date" AT TIME ZONE 'UTC',
ALTER COLUMN "due_date" SET DATA TYPE TIMESTAMPTZ USING "due_date" AT TIME ZONE 'UTC',
ALTER COLUMN "paid_at" SET DATA TYPE TIMESTAMPTZ USING "paid_at" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "webhook_received_at" SET DATA TYPE TIMESTAMPTZ USING "webhook_received_at" AT TIME ZONE 'UTC',
ALTER COLUMN "paid_at" SET DATA TYPE TIMESTAMPTZ USING "paid_at" AT TIME ZONE 'UTC',
ALTER COLUMN "expired_at" SET DATA TYPE TIMESTAMPTZ USING "expired_at" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Subscription" ALTER COLUMN "start_date" SET DATA TYPE TIMESTAMPTZ USING "start_date" AT TIME ZONE 'UTC',
ALTER COLUMN "end_date" SET DATA TYPE TIMESTAMPTZ USING "end_date" AT TIME ZONE 'UTC',
ALTER COLUMN "next_billing_date" SET DATA TYPE TIMESTAMPTZ USING "next_billing_date" AT TIME ZONE 'UTC',
ALTER COLUMN "cancel_date" SET DATA TYPE TIMESTAMPTZ USING "cancel_date" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "reset_token_expires" SET DATA TYPE TIMESTAMPTZ USING "reset_token_expires" AT TIME ZONE 'UTC';
