[Interface]
PrivateKey = 2Pjk8JTbJiVKtNKGROC421xmrg9CHdaH1eC/wsWbEWI=
Address = 10.0.0.20/24
DNS = 1.1.1.1

[Peer]
PublicKey = SP47bTGqXxN4Qqe2DewpONtYEOh2qcXPTj7dt1g1x2o=
Endpoint = 103.196.155.87:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
