DO $$
BEGIN
  CREATE TYPE "MenuScope" AS ENUM ('TENANT', 'PLATFORM');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Menu" ADD COLUMN IF NOT EXISTS "scope" "MenuScope" NOT NULL DEFAULT 'TENANT';
