// List of models to backup (must have tenant_id)
// Ordered by dependency for restore (parent first)
export const TENANT_MODELS = [
    'SystemConfig',
    'Config',
    'StudentCardConfig',
    'TahunPelajaran',
    'Semester',
    'Jurusan',
    'Role',
    'User',
    'Guru',
    'Kelas',
    'Siswa',
    'Mapel',
    'WaliKelas',
    'GuruMapel',
    'KelasMapel',
    'JenisKegiatanMaster',
    'JadwalKBM',
    'StrukturOrganisasi',
    'GuruStrukturOrganisasi',
    'SiswaStrukturOrganisasi',
    'SesiAbsensi',
    'SesiGerbang',
    'AbsenSiswa',
    'AbsenGuru',
    'AbsenGerbangSiswa',
    'JenisPelanggaran',
    'PelanggaranSiswa',
    'SupervisiGuru',
    'OrangTua',
    'Billing',
    'Subscription',
    'Invoice',
    'Payment',
    'RefundRecord',
    'FinancialReport',
    'Document',
    'DocumentActivity',
    'ActivityLog',
    'NotificationLog',
    'NotificationPreference',
    'SiswaFaceTemplate',
    'TenantRiskScore',
    'TenantRiskScoreLog',
    'TenantRiskEvent'
] as const;
