/**
 * HARD RULE:
 * 1 Event = 1 Log Owner
 * No cross logging allowed.
 */

export const ACTIVITY_LOG_ALLOWED_EVENTS = [
  'USER_LOGIN',
  'USER_LOGOUT',
  'USER_CREATED',
  'USER_UPDATED',
  'USER_DELETED',
  'UPGRADE_CLICKED',
  'REPORT_GENERATED',
  'ATTENDANCE_MANUAL_INPUT',
  'PROFILE_UPDATED',
  'ACADEMIC_STUDENT_SYNC',
  'ACADEMIC_TRANSITION_EXECUTE',
  'ACADEMIC_STUDENT_CLASS_CHANGED',
  'COOP_PRODUCT_CREATED',
  'COOP_PRODUCT_UPDATED',
  'COOP_PRODUCT_DELETED',
  'COOP_PRODUCT_ADJUST_STOCK',
  'COOP_PRODUCT_STOCK_IN',
  'COOP_CATEGORY_CREATED',
  'COOP_CATEGORY_UPDATED',
  'COOP_CATEGORY_DELETED',
] as const;

export const AUDIT_LOG_ALLOWED_EVENTS = [
  'billing.subscription.plan_changed',
  'billing.subscription.upgrade_initiated',
  'billing.subscription.upgrade_cancelled',
  'SUBSCRIPTION_STATUS_CHANGED',
  'BILLING_CONFIG_CHANGED',
  'ROLE_MATRIX_UPDATED',
  'TENANT_SUSPENDED_MANUAL',
  'TENANT_UNSUSPENDED_MANUAL',
  'TENANT_DELETED_MANUAL',
  'AUTO_RENEW_TOGGLED',
  'PAYMENT_OVERRIDE',
  'SYSTEM_CONFIG_CHANGED',
  'TENANT_BACKUP_CREATED',
  'TENANT_BACKUP_RESTORED',
  'TENANT_BACKUP_PURGED',
  'TENANT_BACKUP_INTEGRITY_FAILED',
  'INFRA_JOB_MANUAL_RUN',
  'INFRA_JOB_REJECTED_RUNNING',
  'WORKER_START',
  'WORKER_STOP',
  'WORKER_RESTART',
] as const;

export const OBSERVABILITY_ALLOWED_EVENTS = [
  'payment.webhook.processed',
  'payment.failed',
  'PAYMENT_SUCCESS',
  'INVOICE_CREATED',
  'INVOICE_OVERDUE',
  'INVOICE_PAID',
  'SUBSCRIPTION_AUTO_SUSPENDED',
  'SUBSCRIPTION_AUTO_EXTENDED',
  'QUEUE_JOB_FAILED',
  'EMAIL_DELIVERY_FAILED',
  'CRON_EXECUTED',
  'RISK_CALCULATED',
  'FORECAST_CALCULATED',
  'FORECAST_LOCKED',
  'FORECAST_SKIPPED_DUPLICATE',
  'FORECAST_ANOMALY_DOUBLE_ACTIVE',
  'UPGRADE_INTELLIGENCE_CALCULATED',
  'UPGRADE_INTELLIGENCE_LOCKED',
  'UPGRADE_INTELLIGENCE_SKIPPED',
  'UPGRADE_SCORE_CALCULATED',
  'UPGRADE_FUNNEL_COMPUTED',
  'UPGRADE_ANOMALY_HIGH_INTENT_NO_PAYMENT',
  'INFRA_JOB_MANUAL_RUN',
  'INFRA_JOB_REJECTED_RUNNING',
  'INFRA_WORKER_STALLED',
  'INFRA_WORKER_RESTART_TRIGGERED',
  'INFRA_WORKER_RESTART_CRITICAL',
] as const;

export type ActivityLogEvent = (typeof ACTIVITY_LOG_ALLOWED_EVENTS)[number];
export type AuditLogEvent = (typeof AUDIT_LOG_ALLOWED_EVENTS)[number];
export type ObservabilityEvent = (typeof OBSERVABILITY_ALLOWED_EVENTS)[number];
