import { z } from 'zod';

export const createSiswaSchema = z.object({
  nis: z.string().min(1, 'NIS wajib diisi').optional(),
  nisn: z.string().optional().nullable(),
  nik: z.string().optional().nullable(),
  nama_siswa: z.string().min(1, 'Nama Siswa wajib diisi'),
  jenis_kelamin: z.string().min(1, 'Jenis Kelamin wajib diisi'),
  tempat_lahir: z.string().optional().nullable(),
  tanggal_lahir: z.union([z.date(), z.string(), z.number()]).optional().nullable(),
  alamat: z.string().optional().nullable(),
  dusun: z.string().optional().nullable(),
  kelurahan: z.string().optional().nullable(),
  kecamatan: z.string().optional().nullable(),
  kabupaten: z.string().optional().nullable(),
  provinsi: z.string().optional().nullable(),
  rt: z.string().optional().nullable(),
  rw: z.string().optional().nullable(),
  kode_pos: z.string().optional().nullable(),
  no_hp: z.string().optional().nullable(),
  transportasi: z.string().optional().nullable(),
  nama_ayah: z.string().optional().nullable(),
  nik_ayah: z.string().optional().nullable(),
  pekerjaan_ayah: z.string().optional().nullable(),
  pendidikan_ayah: z.string().optional().nullable(),
  penghasilan_ayah: z.string().optional().nullable(),
  nama_ibu: z.string().optional().nullable(),
  nik_ibu: z.string().optional().nullable(),
  pekerjaan_ibu: z.string().optional().nullable(),
  pendidikan_ibu: z.string().optional().nullable(),
  penghasilan_ibu: z.string().optional().nullable(),
  nama_wali: z.string().optional().nullable(),
  hubungan_wali: z.string().optional().nullable(),
  pekerjaan_wali: z.string().optional().nullable(),
  penghasilan_wali: z.string().optional().nullable(),
  anak_ke: z.number().optional().nullable(),
  kebutuhan_khusus: z.string().optional().nullable(),
  penerima_kps: z.boolean().optional().default(false),
  penerima_kip: z.boolean().optional().default(false),
  no_kip: z.string().optional().nullable(),
  kelas_id: z.string().min(1, 'Kelas wajib diisi'),
  tahun_pelajaran_id: z.string().optional().nullable(),
  semester_id: z.string().optional().nullable(),
  no_rfid: z.string().optional().nullable(),
  email: z.string().email('Format email tidak valid').optional().nullable(),
  status: z.string().optional().default('AKTIF'),
  user_id: z.string().optional().nullable(),
  skipQuotaCheck: z.boolean().optional().default(false),
  orang_tua: z.array(z.any()).optional(),
});

export const updateSiswaSchema = createSiswaSchema.partial();

export type CreateSiswaSchema = z.infer<typeof createSiswaSchema>;
export type UpdateSiswaSchema = z.infer<typeof updateSiswaSchema>;
