-- AlterTable
ALTER TABLE "AbsenGerbangSiswa" ALTER COLUMN "waktu_tap" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "AbsenGuru" ALTER COLUMN "waktu_tap" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "AbsenSiswa" ALTER COLUMN "waktu_tap" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "ActivityLog" ALTER COLUMN "timestamp" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "LogTap" ALTER COLUMN "waktu" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "SesiAbsensi" ALTER COLUMN "tanggal" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "waktu_mulai" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "waktu_selesai" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "SesiGerbang" ALTER COLUMN "tanggal" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "waktu_mulai" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "waktu_selesai" SET DATA TYPE TIMESTAMPTZ;
